# Generated by Django 2.2.12 on 2020-06-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
