# Generated by Django 2.2.12 on 2020-06-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_rating_comment_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['comment_updated']},
        ),
    ]
